[server]
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#3DDC97"
backgroundColor = "#0E1116"
secondaryBackgroundColor = "#171C24"
textColor = "#E8EDF4"
font = "sans serif"
